project: cassandra-operator
mode: time-travel
straggler: kind-control-plane3
front-runner: kind-control-plane
operator-pod: cassandra-operator
command: /cassandra-operator
ce-name: sonar-cassandra-datacenter
ce-namespace: default
ce-rtype: cassandradatacenters
ce-diff-current: '{"metadata": {"deletionTimestamp": "SONAR-EXIST", "deletionGracePeriodSeconds":
  0}}'
ce-diff-previous: '{"metadata": {}}'
se-name: data-volume-cassandra-test-cluster-dc1-rack1-0
se-namespace: default
se-rtype: persistentvolumeclaims
se-etype: ADDED
