mode: time-travel
freeze-apiserver: kind-control-plane2
freeze-resource-type: "cassandraoperator.instaclustr.com/v1alpha1, Kind=CassandraDataCenter"
freeze-event-type: DELETED
freeze-duration: 800
restart-pod: cassandra-operator
restart-apiserver: kind-control-plane
restart-resource-type: "cassandraoperator.instaclustr.com/v1alpha1, Kind=CassandraDataCenter"
restart-event-type: ADDED
restart-times: 2
restart-wait: 160
