project: cassandra-operator
mode: time-travel
straggler: kind-control-plane3
ce-name: cassandra-test-cluster-dc1-rack1
ce-rtype: "*apps.StatefulSet"
freeze-event-type: DELETED
freeze-duration: 800
operator-pod: cassandra-operator
front-runner: kind-control-plane
se-rtype: "cassandraoperator.instaclustr.com/v1alpha1, Kind=CassandraDataCenter"
se-etype: DELETED
restart-times: 1
restart-wait: 50
