freeze-apiserver: kind-control-plane3
freeze-crucial-current: '{"metadata": {"deletionTimestamp": "sonar-exist", "deletionGracePeriodSeconds":
  30}}'
freeze-crucial-previous: '{"metadata": {}}'
freeze-resource-name: cassandra-test-cluster-dc1-rack1-1
freeze-resource-namespace: default
freeze-resource-type: pods
mode: time-travel
project: cassandra-operator
restart-apiserver: kind-control-plane
restart-event-type: ADDED
restart-pod: cassandra-operator
restart-resource-name: data-volume-cassandra-test-cluster-dc1-rack1-1
restart-resource-namespace: default
restart-resource-type: persistentvolumeclaims
