project: cassandra-operator
mode: time-travel
straggler: kind-control-plane3
front-runner: kind-control-plane
operator-pod: cassandra-operator
ce-name: cassandra-test-cluster-dc1-rack1-1
ce-namespace: default
ce-rtype: pods
ce-diff-current: '{"metadata": {"deletionTimestamp": "sonar-exist", "deletionGracePeriodSeconds":
  30}}'
ce-diff-previous: '{"metadata": {}}'
se-name: data-volume-cassandra-test-cluster-dc1-rack1-1
se-namespace: default
se-rtype: persistentvolumeclaims
se-etype: ADDED
