project: cassandra-operator
mode: time-travel
freeze-apiserver: kind-control-plane3
freeze-resource-name: cassandra-test-cluster-dc1-rack1-1
freeze-resource-namespace: default
freeze-resource-type: pods
freeze-crucial: "{\"deletionTimestamp\": \"sonar-exist\", \"deletionGracePeriodSeconds\": 30}"
restart-pod: cassandra-operator
restart-apiserver: kind-control-plane
restart-resource-name: data-volume-cassandra-test-cluster-dc1-rack1-1
restart-resource-namespace: default
restart-resource-type: persistentvolumeclaims
restart-event-type: ADDED
