project: zookeeper-operator
mode: time-travel
straggler: kind-control-plane3
front-runner: kind-control-plane
operator-pod: zookeeper-operator
ce-name: sonar-zookeeper-cluster
ce-namespace: default
ce-rtype: zookeeperclusters
ce-diff-current: '{"metadata": {"deletionTimestamp": "sonar-exist", "deletionGracePeriodSeconds":
  0}}'
ce-diff-previous: '{"metadata": {}}'
se-name: data-sonar-zookeeper-cluster-0
se-namespace: default
se-rtype: persistentvolumeclaims
se-etype: ADDED
