project: zookeeper-operator
mode: time-travel
straggler: kind-control-plane3
front-runner: kind-control-plane
operator-pod: zookeeper-operator
ce-name: sonar-zookeeper-cluster
ce-namespace: default
ce-rtype: zookeeperclusters
ce-diff-current: '{"status": {"replicas": 1, "readyReplicas": 1}}'
ce-diff-previous: '{"status": {"replicas": 2, "readyReplicas": 2}}'
se-name: data-sonar-zookeeper-cluster-1
se-namespace: default
se-rtype: persistentvolumeclaims
se-etype: ADDED
