project: zookeeper-operator
mode: time-travel
freeze-apiserver: kind-control-plane3
restart-apiserver: kind-control-plane
restart-pod: zookeeper-operator
freeze-resource-name: sonar-zookeeper-cluster
freeze-resource-namespace: default
freeze-resource-type: zookeeperclusters
freeze-crucial-current: '{"status": {"replicas": 1, "readyReplicas": 1}}'
freeze-crucial-previous: '{"status": {"replicas": 2, "readyReplicas": 2}}'
restart-resource-name: data-sonar-zookeeper-cluster-1
restart-resource-namespace: default
restart-resource-type: persistentvolumeclaims
restart-event-type: ADDED
