project: rabbitmq-operator
mode: time-travel
straggler: kind-control-plane3
front-runner: kind-control-plane
operator-pod: rabbitmq-operator
command: /manager
ce-name: sonar-rabbitmq-cluster
ce-namespace: default
ce-rtype: rabbitmqcluster
ce-diff-current: '{"metadata": {"deletionTimestamp": "SONAR-EXIST", "deletionGracePeriodSeconds":
  0}}'
ce-diff-previous: '{"metadata": {}}'
se-name: sonar-rabbitmq-cluster-server
se-namespace: default
se-rtype: statefulset
se-etype: ADDED
