project: rabbitmq-operator
mode: time-travel
straggler: kind-control-plane3
front-runner: kind-control-plane
operator-pod: rabbitmq-operator
command: /manager
ce-name: sonar-rabbitmq-cluster
ce-namespace: default
ce-rtype: rabbitmqcluster
ce-diff-current: '{"metadata": {"annotations": {"kubectl.kubernetes.io/last-applied-configuration":
  "{\"apiVersion\":\"rabbitmq.com/v1beta1\",\"kind\":\"RabbitmqCluster\",\"metadata\":{\"annotations\":{},\"name\":\"sonar-rabbitmq-cluster\",\"namespace\":\"default\"},\"spec\":{\"persistence\":{\"storage\":\"15Gi\"},\"replicas\":1}}\n"}},
  "spec": {"persistence": {"storage": "15Gi"}}}'
ce-diff-previous: '{"metadata": {"annotations": {"kubectl.kubernetes.io/last-applied-configuration":
  "{\"apiVersion\":\"rabbitmq.com/v1beta1\",\"kind\":\"RabbitmqCluster\",\"metadata\":{\"annotations\":{},\"name\":\"sonar-rabbitmq-cluster\",\"namespace\":\"default\"},\"spec\":{\"replicas\":1}}\n"}},
  "spec": {"persistence": {"storage": "10Gi"}}}'
ce-etype-current: Updated
ce-etype-previous: Updated
se-name: sonar-rabbitmq-cluster-server
se-namespace: default
se-rtype: statefulset
se-etype: ADDED
description: 'Pause kind-control-plane3 after it processes a default/rabbitmqcluster/sonar-rabbitmq-cluster
  event E. E should match the pattern {"metadata": {"annotations": {"kubectl.kubernetes.io/last-applied-configuration":
  "{\"apiVersion\":\"rabbitmq.com/v1beta1\",\"kind\":\"RabbitmqCluster\",\"metadata\":{\"annotations\":{},\"name\":\"sonar-rabbitmq-cluster\",\"namespace\":\"default\"},\"spec\":{\"persistence\":{\"storage\":\"15Gi\"},\"replicas\":1}}\n"}},
  "spec": {"persistence": {"storage": "15Gi"}}} and the events before E should match
  {"metadata": {"annotations": {"kubectl.kubernetes.io/last-applied-configuration":
  "{\"apiVersion\":\"rabbitmq.com/v1beta1\",\"kind\":\"RabbitmqCluster\",\"metadata\":{\"annotations\":{},\"name\":\"sonar-rabbitmq-cluster\",\"namespace\":\"default\"},\"spec\":{\"replicas\":1}}\n"}},
  "spec": {"persistence": {"storage": "10Gi"}}}. And restart the controller rabbitmq-operator
  after kind-control-plane processes a ADDED default/statefulset/sonar-rabbitmq-cluster-server
  event.'
